{% set name = "HiGHS" %}
{% set version = "1.10.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cf29873b894133bac111fc45bbf10989b6c5c041992fcd10e31222253e371a4c

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja  # [win]
    - make  # [not win]
    - {{ stdlib("c") }}
  run:
    - python >={{ python_min }}
    - numpy

test:
  source_files:
    - check/instances/afiro.mps
  commands:
    - test -f ${PREFIX}/include/highs/Highs.h  # [unix]
    - test -f ${PREFIX}/lib/libhighs.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)  # [win]
    - highs check/instances/afiro.mps

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://highs.dev
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - galabovaa
    - adament
    - julian-belina
    - DerThorsten
