{% set name = "HiGHS" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e184e63101cf19688a02102f58447acc7c021d77eef0d3475ceaceb61f035539

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [unix]
    - {{ stdlib("c") }}
  run:
    # Should be limited to python >=3.8 but is not allowed
    - python
    - numpy

test:
  commands:
    - test -f ${PREFIX}/include/highs/Highs.h  # [unix]
    - test -f ${PREFIX}/lib/libhighs.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)  # [win]

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://highs.dev
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - julian-belina
    - DerThorsten
