schema_version: 1

context:
  name: HiGHS
  version: 1.10.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ERGO-Code/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cf29873b894133bac111fc45bbf10989b6c5c041992fcd10e31222253e371a4c

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake >=3.15
    - if: win
      then: ninja
    - if: not win
      then: make
    - ${{ stdlib("c") }}

tests:
  - files:
      source:
        - check/instances/afiro.mps
    script:
      - if: unix
        then: test -f ${PREFIX}/include/highs/Highs.h
      - if: linux
        then: test -f ${PREFIX}/lib/libhighs.so
      - if: win
        then: if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)
      - highs check/instances/afiro.mps

about:
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/ERGO-Code/HiGHS
  repository: https://github.com/ERGO-Code/HiGHS
  documentation: https://highs.dev

extra:
  recipe-maintainers:
    - galabovaa
    - adament
    - julian-belina
    - DerThorsten
